title: Qurban
code: '<i class="fas fa-hamburger fa-2x text-danger"></i>'
updated_by: a7098d2c-c4b1-4681-bfbc-3a7f4d2bd583
updated_at: 1677910186
blueprint: category
icon: '<i class="fas fa-hamburger fa-2x text-danger"></i>'
