title: Service
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          antlers: false
          display: Description
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: side_images
        field:
          mode: list
          container: assets
          restrict: true
          allow_uploads: true
          show_filename: true
          max_files: 4
          display: 'Side Images'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
            - 'min:4'
          folder: service
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
