sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          antlers: false
          display: Description
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: price
        field:
          input_type: number
          antlers: false
          display: Price
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: image
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
            - 'min:1'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Product
